"""Async Neo4j connector for the GraphRAG pipeline.

Provides a thin execution layer: entity resolution queries via
``find_nodes_by_values`` and generic parameterized Cypher execution via
``run_query``.  All domain-specific Cypher is generated by the
``CypherBuilder`` — the connector never constructs Cypher from user input.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from neo4j import AsyncGraphDatabase

from app.bioblend_server.GraphRAG.schema import NODE_ID_FIELDS

# ---------------------------------------------------------------------------
# Cypher name validation
# ---------------------------------------------------------------------------

SAFE_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _validate_cypher_name(name: str) -> str:
    """Reject names that are not safe to interpolate into Cypher identifiers."""
    if not SAFE_NAME.match(name):
        raise ValueError(f"Unsafe Cypher name: {name!r}")
    return name


def _canonical_id(
    label: str,
    properties: dict[str, Any],
    fallback_id: str = "",
) -> str:
    """Generate a canonical ID for a node based on its label and properties."""
    id_fields = NODE_ID_FIELDS.get(label, ["id"])
    for field_name in id_fields:
        value = properties.get(field_name)
        if value is not None and str(value).strip():
            return f"{label}:{value}"
    if fallback_id:
        return f"{label}:{fallback_id}"
    return f"{label}:unknown"


# ---------------------------------------------------------------------------
# Connector
# ---------------------------------------------------------------------------


class Neo4jGraphConnector:
    """Async Neo4j connector using ``elementId()`` for node identification.

    This connector is intended to be long-lived (one per application) so that
    the underlying driver connection pool is reused across requests.
    """

    def __init__(
        self,
        uri: str,
        user: str,
        password: str,
        database: str | None = None,
    ) -> None:
        self.log = logging.getLogger(self.__class__.__name__)
        self.database = database
        self.driver = AsyncGraphDatabase.driver(uri, auth=(user, password))

    async def close(self) -> None:
        try:
            self.log.info("Closing Neo4j driver")
            await self.driver.close()
        except Exception as error:
            self.log.error(f"Error closing Neo4j driver: {error}", exc_info=True)

    # ------------------------------------------------------------------
    # Generic query execution
    # ------------------------------------------------------------------

    async def run_query(
        self,
        query: str,
        parameters: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """Execute a parameterized Cypher query and return result rows.

        Raises on failure so callers (the executor) can distinguish "no results"
        from "query failed" and record the real error in debug traces.
        """
        self.log.debug(f"Running query with parameters: {parameters}")
        async with self.driver.session(database=self.database) as session:
            result = await session.run(query, parameters or {})
            data = [record.data() async for record in result]
            self.log.debug(f"Query returned {len(data)} rows")
            return data

    # ------------------------------------------------------------------
    # Entity resolution (used by EntityResolver before LLM planning)
    # ------------------------------------------------------------------

    async def find_nodes_by_values(
        self,
        label: str,
        exact_props: list[str],
        fuzzy_props: list[str],
        values: list[str],
    ) -> list[dict[str, Any]]:
        """Find nodes by exact and/or fuzzy property matching.

        Returns a list of node dicts with keys: id, label, properties, element_id.
        """
        try:
            if not values or (not exact_props and not fuzzy_props):
                return []

            safe_label = _validate_cypher_name(label)
            clauses: list[str] = []
            params: dict[str, Any] = {}

            if exact_props:
                typed_values: list[Any] = []
                for v in values:
                    typed_values.append(v)
                    if v.isdigit():
                        typed_values.append(int(v))
                    elif v.replace(".", "", 1).isdigit() and v.count(".") == 1:
                        typed_values.append(float(v))

                params["exact_values"] = typed_values

                for prop in exact_props:
                    safe_prop = _validate_cypher_name(prop)
                    clauses.append(f"n.{safe_prop} IN $exact_values")

            if fuzzy_props:
                for i, val in enumerate(values):
                    params[f"fuzz_val_{i}"] = str(val).lower()
                    for prop in fuzzy_props:
                        safe_prop = _validate_cypher_name(prop)
                        clauses.append(
                            f"toLower(toString(n.{safe_prop})) CONTAINS $fuzz_val_{i}"
                        )

            if not clauses:
                return []

            where_clause = " OR ".join(clauses)
            query = (
                f"MATCH (n:{safe_label}) "
                f"WHERE {where_clause} "
                "RETURN labels(n)[0] AS label, properties(n) AS properties, "
                "elementId(n) AS element_id "
                "LIMIT 100"
            )

            rows = await self.run_query(query, params)
            return [self._row_to_node(row) for row in rows]
        except Exception as error:
            self.log.error(f"Error in find_nodes_by_values: {error}", exc_info=True)
            return []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _row_to_node(row: dict[str, Any]) -> dict[str, Any]:
        label = str(row.get("label", "Unknown"))
        properties = row.get("properties", {}) or {}
        element_id = str(row.get("element_id", ""))
        node_id = _canonical_id(label, properties, fallback_id=element_id)
        return {
            "id": node_id,
            "label": label,
            "properties": properties,
            "element_id": element_id,
        }
